on:
  workflow_dispatch:
    inputs:
      start_index:
        description: '开始编号'
        required: true
        default: '81'

jobs:
  call-matrix-workflow:
    uses: Buc014960kPearson/Buc014960kPearson/.github/workflows/dynamic-matrix-runner.yml@main
    with:
      start_index: ${{ inputs.start_index }}
